sudo: required
language: bash

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8

branches:
  only:
    - master

before_script:
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - git clone --recursive https://github.com/egel/dotfiles.git ~/.dotfiles

script:
  - ~/.dotfiles/bin/dotfiles install -y
