language: bash

sudo: required
dist: trusty

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git clone --recursive https://github.com/egel/dotfiles.git ~/.dotfiles

script:
  - ~/.dotfiles/bin/dotfiles install -y
