language: bash
sudo: required
dist: xenial

before_cache:
  - rm -rf $HOME/.cache

cache:
  bundler: false

before_script:
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" && -f "/etc/init.d/xvfb" ]]; then sh -e /etc/init.d/xvfb start; fi
  - rm -rf ~/.dotfiles
  - git clone --recursive https://github.com/egel/dotfiles.git ~/.dotfiles

script:
  - ~/.dotfiles/bin/dotfiles install -y
